language: ruby
rvm:
  - 2.2.2
addons:
    apt:
        packages:
            - python-sphinx
before_install: gem install bundler -v 1.11.2
install:
    - bundle install --jobs=3 --retry=3
script:
    - bundle exec rake test
